### ISSUE TITLE
[Feature Request] Allow to specify more than one table in a backup request

### ISSUE THREAD

**Issue by cscetbon** [instaclustr/cassandra-backup#16]
in BackupOperationRequest keys-aces is a list but not table https://github.com/instaclustr/cassandra-backup/blob/5ff9c1b685e0f9345ca76133cf1d748c17a0aa4e/src/main/java/com/instaclustr/cassandra/backup/impl/backup/BackupOperationRequest.java#L54. We could use a list to allow the backup of multiple tables using the same configuration/tag.

If a keyspace is specified, then all tables specified would be automatically prefixed by that except those already prefixed. Otherwise we could even not define keyspaces and provide a list of table names prefixed with keyspace names. Here are a few examples of what I can envision :

```
keyspaces: 
  - k1
tables:
  - t1  # --> will backup k1.t1
  - t2 # --> will backup k1.t2
```

```
keyspaces: 
  - k1
tables:
  - t1  # --> will backup k1.t1
  - k2.t2 # --> will backup k2.t2
```

```
keyspaces: 
tables:
  - k1.t1  # --> will backup k1.t1
  - k2.t2 # --> will backup k2.t2
```

```
keyspaces: 
  - k1
  - k2
tables: # --> will backup all tables in k1 and k2
```

**Comment by smiklosovic** [comment]
Hi @cscetbon ,

what about having just one property / flag / option / field which would be a string separated by commas and we would parse it ... for example

```
k1,k2
k1,k2.t1,k2.t2
```

The end goal is to make one field from two, currently there is keyspace and  tables, we would have just one ... 

Sounds good?

**Comment by cscetbon** [comment]
@smiklosovic, yes it sounds good to me.

**Comment by smiklosovic** [comment]
@cscetbon for the sake of simplicity, you will be able to backup _either_ whole keyspaces only _or_ tables. In other words, one can not mix whole keyspaces with tables simultaneously,

```
this is possible ->
k1,k2,k3

this is possible too ->
k1.c1,k2.c2,k3.c3

this is not possible ->
k1,k2.c2
```

This is not my idea, if you see how JMX method is done on Storage service, it is supporting this scenario only as well:

https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/service/StorageServiceMBean.java#L221-L224

**Comment by cscetbon** [comment]
yeah @smiklosovic, I can see it, fair enough 👍 

```
nodetool snapshot -t test3 -kt demo.t1 -- system
error: When specifying the Keyspace columfamily list for a snapshot, you should not specify columnfamily
-- StackTrace --
java.io.IOException: When specifying the Keyspace columfamily list for a snapshot, you should not specify columnfamily
	at org.apache.cassandra.tools.nodetool.Snapshot.execute(Snapshot.java:73)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:283)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.accept(NodeTool.java:268)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.accept(NodeTool.java:245)
	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:182)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:54)
```

**Comment by smiklosovic** [comment]
implemented here https://github.com/instaclustr/cassandra-backup/pull/22

**Comment by cscetbon** [comment]
Good job @smiklosovic 👏
