### ISSUE TITLE
Allow to not specify secrets even if it is running in a kubernetes cluster

### ISSUE THREAD

**Issue by puneetloya** [instaclustr/cassandra-backup#19]
ERROR com.instaclustr.cassandra.backup.cli.BackupApplication - This code is running in Kubernetes or as a Kubernetes client but there is not 'k8sSecretName' field set on backup request!

can this be upto the user if they want to specify a kubernetes secret?

**Comment by smiklosovic** [comment]
@puneetloya sure I ll introduce some flag, do you want me to release it too or are you fine with snapshot for a while?

**Comment by smiklosovic** [comment]
@puneetloya how do you want to invoke a backup then? where do you read these secrets from? or do you use local backuper which does not require you to provide a secret?

**Comment by puneetloya** [comment]
a flag is great. I am supplying secrets as environment variable. 

Can the flag be something like running-as-client or running-as-kubernetes? If not the default behavior you have

Release is not required.

**Comment by puneetloya** [comment]
I am invoking the backup similar to what cassandra-sidecar project has? A bare bones http server to run the backup command.

**Comment by smiklosovic** [comment]
@puneetloya pull master branch of this repo and build it, I have just pushed this 

That component was just released and this is introduced there (2)

You have to set `pretend.not.running.in.kubernetes` to `true` as system property to override the default behaviour.

If you use cassandra-sidecar, you have to build this project and update cassandra-backup version there to 1.1.9-SNAPSHOT and build it. (3)

I can do it tomorrow for you and release it if you just dont know how to proceeed.

(1) https://github.com/instaclustr/cassandra-backup/commit/0738bc4b21c3133bb9de33de95df7d28ce803a73
(2) https://github.com/instaclustr/instaclustr-commons/blob/20cbd7625bc6c4c1a6693c5bd692aa06b807991a/src/main/java/com/instaclustr/kubernetes/KubernetesHelper.java#L24

(3) https://github.com/instaclustr/cassandra-sidecar/blob/master/pom.xml#L85

**Comment by puneetloya** [comment]
basically I set -Dpretend.not.running.in.kubernetes=true right?

**Comment by smiklosovic** [comment]
pretty much
