### ISSUE TITLE
Avoid using ListBuckets to determine if a bucket exits

### ISSUE THREAD

**Issue by bassamchahine** [instaclustr/cassandra-backup#29]
Since ListBuckets can be used to gather information about a system, it is considered to be a security risk in some production environments.  

cassandra-backup uses ListBuckets to verify if a specific bucket exists.  This can be replaced by doesBucketExistV2 and remove the dependency on ListBuckets.

**Comment by smiklosovic** [comment]
Closing as it is part of 2.0.0-alpha6
