### ISSUE TITLE
Procedure of restore

### ISSUE THREAD

**Issue by ahmedjami** [instaclustr/cassandra-backup#5]
Hello,
I begin with cassandra-backup and I have a question about the restore method.
Related to the documentation, the restore consists of a "copy" of sstables files then a refresh. 

Does that mean, there is no a method like backupTask that launch the restore via the java application ? 

Thanks.

**Comment by smiklosovic** [comment]
Hi @ahmedjami 

We have rewritten the backup solution. You can consult README to know more about this software.
