### ISSUE TITLE
Automatically create a bucket for cloud storage when it does not exist

### ISSUE THREAD

**Issue by smiklosovic** [instaclustr/cassandra-backup#6]

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-backup/commit/72dc750cc3c62facfbec3b0f180307644eea4f8a

**Comment by zegelin** [comment]
Was this implemented at the request of a user?

**Comment by smiklosovic** [comment]
No. However I can make a flag on cli which would turn it _on_, it would be turned off by default. Is that something you would like to see?

**Comment by zegelin** [comment]
Yes that would be useful. Some environments lock down various API calls, such as `ListBuckets`, causing this feature to fail.

**Comment by smiklosovic** [comment]
Closing as it is part of 2.0.0-alpha6
